In [3]:
import torch
import torch.distributions as dist

In [9]:
## Let's create a Bernoulli distribution -> has only 2 outcomes

bernoulli = dist.Bernoulli(torch.tensor([0.5]))
print(bernoulli)

## Sample from distribution
for _ in range(10):
    print(bernoulli.sample())

Bernoulli(probs: tensor([0.5000]))
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])


In [12]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.5180000066757202
Variance: 0.24992592632770538


In [13]:
## Let's create a Gaussian/Normal Distribution

normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0])) # mean is 0 and SD is 1
for _ in range(10):
    print(normal.sample())

tensor([0.2743])
tensor([0.7088])
tensor([-2.4953])
tensor([-1.0193])
tensor([0.3069])
tensor([0.1894])
tensor([-0.2644])
tensor([-0.1316])
tensor([1.1115])
tensor([1.3854])


In [14]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.0011930199107155204
Variance: 1.0008480548858643


In sampling any probability distributions, as we are getting only few of the samples and not the whole distribution, hence, the mean and variance won't match perfectly.